spring:
  jwt:
    secret: ${JWT_SECRET}
    expirationMs: ${JWT_EXPIRATION_MS} # 1 day
  datasource:
    url: jdbc:postgresql://localhost:5432/backpicker
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true